### ISSUE TITLE
API changes.. ! - Platform upgrage notice!

### ISSUE THREAD

**Issue by Ilovegym66** [raschy/ioBroker.solarmanpv#66]
Hello, I got from the solarmanpv support this email:
`
Dear valued customer,

We are delighted to inform you that SOLARMAN platform will upgrade data centers from 2023-04-16 09:00 to 2023-04-16 18:00 (UTC+8) , as part of our continued efforts to offer you a premium product.

Please note that  your account and data will not be accessible via the interface until the upgrade is completed.

Once upgrade is completed, if you are using the "International Data Center", we kindly remind that you use the new OPENAPI domain [https://globalapi.solarmanpv.com](https://tracedm.aliyun.com/trace/v1/report?bid=--sensibledatadeleted) to access the platform, replacing the previous domain [https://api.solarmanpv.com](https://tracedm.aliyun.com/trace/v1/report?bid=sensibledatadeleted). Your APPID and APPSECRET will remain the same, but you will need to obtain a new token to access the platform.

If you require historical data during the upgrade, we recommend that you use the historical data interface (Interface 3.4 and Interface 4.3) to supplement it after the upgrade is completed.

Should you have any questions or concerns, please do not hesitate to contact us at [customerservice@solarmanpv.com](mailto:customerservice@solarmanpv.com).

Thank you for choosing SOLARMAN platform, and we look forward to providing you with an even better user experience.

Sincerely,

The SOLARMAN Team
`

**Comment by raschy** [comment]
Thanks for the info. I have received an identical email. I hope that the old api interface will continue to run for a while and that the api itself has not been changed much. Otherwise, I will implement and publish the changes as soon as possible.

**Comment by m0uh85** [comment]
They switched back to the old API - since this night no more data :(

Dear valued customer,

We are very sorry that upgrade of date centers wasn't as successful as expected on 16th, April and you have to use previous OPENAPI domain.

Now we are delighted to inform you that we have successfully upgrade data centers. If you are using the "International Data Center", we kindly remind that you use the new OPENAPI domain [https://globalapi.solarmanpv.com](https://tracedm.aliyun.com/trace/v1/report?bid=1436598&env=600000019920593402&mac=248056&mf=upgrade%40upgrade.solarmanpv.com&msgid=14816b42-5304-4438-a073-886ddae66b6d%40alibaba.com&sac=0&tag=mail3&tid=1436598&to=matze%40inked-mawi.de&tpl=&ts=1681762345&type=0&url=https%3A%2F%2Fglobalapi.solarmanpv.com%2F&v=1.0&sign=7bbbe6083c1f5bb19f552846c1facb38) to access the platform, replacing the previous domain [https://api.solarmanpv.com](https://tracedm.aliyun.com/trace/v1/report?bid=1436598&env=600000019920593402&mac=248056&mf=upgrade%40upgrade.solarmanpv.com&msgid=14816b42-5304-4438-a073-886ddae66b6d%40alibaba.com&sac=0&tag=mail3&tid=1436598&to=matze%40inked-mawi.de&tpl=&ts=1681762345&type=0&url=https%3A%2F%2Fapi.solarmanpv.com%2F&v=1.0&sign=93f092eb1ffbd795484a668b585c03b5). Your APPID and APPSECRET will remain the same, but you will need to obtain a new token to access the platform.

If you require historical data during the upgrade, we recommend that you use the historical data interface (Interface 3.4 and Interface 4.3) to supplement it after the upgrade is completed.

Should you have any questions or concerns, please do not hesitate to contact us at [customerservice@solarmanpv.com](mailto:customerservice@solarmanpv.com).

Thank you for choosing SOLARMAN platform, and we look forward to providing you with an even better user experience.

Sincerely,

The SOLARMAN Team

**Comment by raschy** [comment]
m0uh85 Try version 0.4.0 since today. It should works.

**Comment by m0uh85** [comment]
> m0uh85 Try version 0.4.0 since today. It should works.

Im updated already to 0.4.0

But they wrote the update was not successfull - since 0:06 I don't recieve any data.

OK - now it works. Sorry!
